# Generated by Django 4.2.7 on 2023-11-28 18:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spacefy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Username should contain at least 2 characters!')])),
                ('slug', models.SlugField(unique=True)),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='First name should contain at least 2 characters!')])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Last name should contain at least 2 characters!')])),
                ('avatar', models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics')),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('friends', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spacefy.friend')),
                ('photos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spacefy.photo')),
                ('posts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spacefy.post')),
                ('stories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spacefy.story')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
