version: '3'

services:
  postgres:
        restart: unless-stopped
        image: postgres:15
        env_file:
          - .env
        volumes:
          - postgres_data:/var/lib/postgresql/data/
        networks:
          - network

volumes:
    postgres_data:
networks:
  network:
    driver: bridge