# Generated by Django 4.2.8 on 2023-12-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacefy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked_object_id',
            field=models.IntegerField(unique=True),
        ),
    ]
