# Generated by Django 4.2.7 on 2023-12-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacefy', '0002_story_creared_at_story_story_story_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story',
            field=models.FileField(upload_to='stories'),
        ),
    ]
