# Generated by Django 4.2.7 on 2023-12-14 20:07

import apps.spacefy.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacefy', '0003_alter_story_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story',
            field=models.FileField(upload_to='stories', validators=[apps.spacefy.validators.file_size_validator, apps.spacefy.validators.file_type_validator]),
        ),
    ]
